### ISSUE TITLE
s/css class names in node/express

### ISSUE THREAD

**Issue by dyspop** [ajlkn/skel#174]
correct me if i'm missing something but i can't seem to work around the fact that this framework uses invalid class names (which browsers don't care about when loaded as css) and node won't have this.

index.pug:
`.six.actions.vertical.signup-email.6u$.12u$(xsmall)`

but at express app run 
```

Error: /Users/danielblack/code/dan.black/views/index.pug:139:47

 > 139|             .six.actions.vertical.signup-email.6u$.12u$(xsmall)
-------------------------------------------------------^

Class names must begin with "-", "_" or a letter.
   at makeError (/Users/danielblack/code/dan.black/node_modules/pug-error/index.js:32:13)
   at Lexer.error (/Users/danielblack/code/dan.black/node_modules/pug-lexer/index.js:58:15)
   at Lexer.className (/Users/danielblack/code/dan.black/node_modules/pug-lexer/index.js:416:12)
   at Lexer.callLexerFunction (/Users/danielblack/code/dan.black/node_modules/pug-lexer/index.js:1315:23)
   at Lexer.advance (/Users/danielblack/code/dan.black/node_modules/pug-lexer/index.js:1351:15)
   at Lexer.callLexerFunction (/Users/danielblack/code/dan.black/node_modules/pug-lexer/index.js:1315:23)
   at Lexer.getTokens (/Users/danielblack/code/dan.black/node_modules/pug-lexer/index.js:1371:12)
   at lex (/Users/danielblack/code/dan.black/node_modules/pug-lexer/index.js:12:42)
   at Object.load.string.lex (/Users/danielblack/code/dan.black/node_modules/pug/lib/index.js:93:27)
   at Function.loadString [as string] (/Users/danielblack/code/dan.black/node_modules/pug-load/index.js:44:24)
```

the important bit being: `Class names must begin with "-", "_" or a letter.`

**Comment by ajlkn** [comment]
Does it let you unicode escape class names (eg. `.\36 u` instead of `6u`)?

**Comment by pogan** [comment]
Had the same problem here. The workaround is quite trivial

**Comment by pogan** [comment]
Had the same problem. The workaround is quite trivial.
Instead of having:
`.6u(class='12u(narrower)')`
Do
`div(class='6u 12u(narrower))`
